import React, { useState } from 'react';
import { Layout, Smartphone, Monitor, ChevronRight, Sparkles, CheckCircle2, Compass, Palette, Type } from 'lucide-react';
import { DesignSpec, DesignScreen } from '../../types/api';

interface PrototypePreviewProps {
  designSpec: DesignSpec;
}

export const PrototypePreview: React.FC<PrototypePreviewProps> = ({ designSpec }) => {
  const spec = designSpec.design;
  const screens = spec?.screens || [];
  const [activeScreenIndex, setActiveScreenIndex] = useState<number>(0);
  const [activeTab, setActiveTab] = useState<'screens' | 'flows' | 'system'>('screens');

  const activeScreen: DesignScreen | undefined = screens[activeScreenIndex] || screens[0];

  return (
    <div className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden">
      {/* Preview Header */}
      <div className="bg-slate-900 text-white p-5 md:p-6 flex flex-wrap items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <span className="px-2.5 py-0.5 rounded-full text-xs font-bold bg-pink-500/20 text-pink-300 border border-pink-500/30">
              Interactive Product Preview v{designSpec.version}
            </span>
            <span className="text-xs text-slate-400">
              Generated by Sofia Designer
            </span>
          </div>
          <h3 className="text-lg md:text-xl font-bold text-white mt-1">
            {spec?.productExperienceSummary || designSpec.summary}
          </h3>
        </div>

        {/* View mode tabs */}
        <div className="flex items-center gap-1 bg-slate-800 p-1 rounded-xl border border-slate-700">
          <button
            type="button"
            onClick={() => setActiveTab('screens')}
            className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold transition-all ${
              activeTab === 'screens' ? 'bg-pink-600 text-white shadow-sm' : 'text-slate-400 hover:text-white'
            }`}
          >
            <Monitor className="w-3.5 h-3.5" />
            Screens ({screens.length})
          </button>
          <button
            type="button"
            onClick={() => setActiveTab('flows')}
            className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold transition-all ${
              activeTab === 'flows' ? 'bg-pink-600 text-white shadow-sm' : 'text-slate-400 hover:text-white'
            }`}
          >
            <Compass className="w-3.5 h-3.5" />
            User Flows ({spec?.userFlows?.length || 0})
          </button>
          <button
            type="button"
            onClick={() => setActiveTab('system')}
            className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold transition-all ${
              activeTab === 'system' ? 'bg-pink-600 text-white shadow-sm' : 'text-slate-400 hover:text-white'
            }`}
          >
            <Palette className="w-3.5 h-3.5" />
            Design Tokens
          </button>
        </div>
      </div>

      {/* Main Content Area */}
      <div className="p-6">
        {activeTab === 'screens' && (
          <div>
            {/* Screen Picker Tabs */}
            <div className="flex items-center gap-2 overflow-x-auto pb-3 mb-6 border-b border-slate-100">
              {screens.map((screen, idx) => (
                <button
                  key={screen.id || idx}
                  type="button"
                  onClick={() => setActiveScreenIndex(idx)}
                  className={`flex items-center gap-2 px-4 py-2 rounded-xl text-xs font-semibold whitespace-nowrap transition-all ${
                    activeScreenIndex === idx
                      ? 'bg-indigo-50 border-2 border-indigo-600 text-indigo-900 shadow-sm'
                      : 'bg-slate-50 border border-slate-200 text-slate-600 hover:bg-slate-100'
                  }`}
                >
                  <span>{screen.name}</span>
                  <span className="font-mono text-[10px] text-slate-400 bg-white px-1.5 py-0.5 rounded border border-slate-200">
                    {screen.route}
                  </span>
                </button>
              ))}
            </div>

            {/* Wireframe Preview Canvas */}
            {activeScreen && (
              <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                {/* Left 2 Cols: Screen Wireframe Mockup */}
                <div className="lg:col-span-2 bg-slate-50 border-2 border-dashed border-slate-300 rounded-2xl p-6 relative">
                  {/* Wireframe Browser Header */}
                  <div className="flex items-center justify-between pb-4 border-b border-slate-200 mb-6">
                    <div className="flex items-center gap-2">
                      <div className="w-3 h-3 rounded-full bg-rose-400" />
                      <div className="w-3 h-3 rounded-full bg-amber-400" />
                      <div className="w-3 h-3 rounded-full bg-emerald-400" />
                      <span className="text-xs font-mono text-slate-400 ml-2">https://app.taydau.internal{activeScreen.route}</span>
                    </div>
                    <span className="text-xs font-semibold text-slate-500 bg-white px-2.5 py-1 rounded-md border border-slate-200">
                      Primary User: {activeScreen.primaryUser}
                    </span>
                  </div>

                  {/* Wireframe Sections */}
                  <div className="space-y-4">
                    <div className="flex items-center justify-between bg-white p-4 rounded-xl border border-slate-200 shadow-sm">
                      <div>
                        <h4 className="font-bold text-slate-900 text-base">{activeScreen.name}</h4>
                        <p className="text-xs text-slate-500">{activeScreen.purpose}</p>
                      </div>
                      <div className="flex items-center gap-2">
                        {activeScreen.primaryActions?.map((act, i) => (
                          <button
                            key={i}
                            type="button"
                            className="px-3 py-1.5 bg-indigo-600 text-white text-xs font-semibold rounded-lg shadow-sm"
                          >
                            {act}
                          </button>
                        ))}
                      </div>
                    </div>

                    {/* Visual Wireframe Layout Boxes */}
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                      {activeScreen.sections?.map((sec, i) => (
                        <div key={i} className="bg-white p-4 rounded-xl border border-slate-200 shadow-sm">
                          <span className="text-[10px] font-bold text-indigo-600 uppercase tracking-wider block mb-1">
                            Section {i + 1}
                          </span>
                          <h5 className="font-semibold text-slate-800 text-sm mb-2">{sec}</h5>
                          <div className="h-14 bg-slate-100 rounded-lg flex items-center justify-center text-xs text-slate-400 border border-dashed border-slate-200">
                            Interactive Content Container
                          </div>
                        </div>
                      ))}
                    </div>

                    {/* Wireframe Elements Checklist */}
                    {activeScreen.wireframeElements && activeScreen.wireframeElements.length > 0 && (
                      <div className="bg-white p-4 rounded-xl border border-slate-200">
                        <span className="text-xs font-bold text-slate-700 block mb-2">Wireframe Components:</span>
                        <div className="flex flex-wrap gap-2">
                          {activeScreen.wireframeElements.map((el, i) => (
                            <span key={i} className="text-xs bg-slate-100 text-slate-700 px-2.5 py-1 rounded-md font-medium">
                              {el}
                            </span>
                          ))}
                        </div>
                      </div>
                    )}
                  </div>
                </div>

                {/* Right Col: Screen Metadata & UX Details */}
                <div className="space-y-4">
                  <div className="bg-slate-50 p-5 rounded-2xl border border-slate-200">
                    <h5 className="font-bold text-slate-900 text-sm mb-3">Screen Purpose</h5>
                    <p className="text-xs text-slate-600 leading-relaxed mb-4">{activeScreen.purpose}</p>

                    <h5 className="font-bold text-slate-900 text-xs uppercase tracking-wider mb-2">Primary User</h5>
                    <p className="text-xs font-semibold text-indigo-700 bg-indigo-50 px-2.5 py-1 rounded-lg inline-block mb-4">
                      {activeScreen.primaryUser}
                    </p>

                    <h5 className="font-bold text-slate-900 text-xs uppercase tracking-wider mb-2">Primary Actions</h5>
                    <ul className="space-y-1.5">
                      {activeScreen.primaryActions?.map((act, i) => (
                        <li key={i} className="text-xs text-slate-700 flex items-center gap-2">
                          <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600 shrink-0" />
                          <span>{act}</span>
                        </li>
                      ))}
                    </ul>
                  </div>

                  <div className="bg-indigo-50/50 p-4 rounded-2xl border border-indigo-100 text-xs text-slate-600">
                    <span className="font-bold text-indigo-900 block mb-1">Responsive Behavior:</span>
                    {spec?.responsiveBehavior || 'Mobile-first layout with fluid grids and touch-friendly controls.'}
                  </div>
                </div>
              </div>
            )}
          </div>
        )}

        {/* User Flows Tab */}
        {activeTab === 'flows' && (
          <div className="space-y-6">
            {spec?.userFlows?.map((flow, i) => (
              <div key={i} className="bg-slate-50 p-6 rounded-2xl border border-slate-200">
                <h4 className="font-bold text-slate-900 text-base mb-4 flex items-center gap-2">
                  <Compass className="w-4 h-4 text-pink-600" />
                  {flow.name}
                </h4>
                <div className="flex flex-wrap items-center gap-2">
                  {flow.steps?.map((step, sIdx) => (
                    <React.Fragment key={sIdx}>
                      <div className="bg-white px-4 py-2.5 rounded-xl border border-slate-200 shadow-sm text-xs font-semibold text-slate-800 flex items-center gap-2">
                        <span className="w-5 h-5 rounded-full bg-pink-100 text-pink-800 flex items-center justify-center text-[10px] font-bold">
                          {sIdx + 1}
                        </span>
                        <span>{step}</span>
                      </div>
                      {sIdx < flow.steps.length - 1 && (
                        <ChevronRight className="w-4 h-4 text-slate-400 shrink-0" />
                      )}
                    </React.Fragment>
                  ))}
                </div>
              </div>
            ))}
          </div>
        )}

        {/* Design System Tokens Tab */}
        {activeTab === 'system' && spec?.designSystem && (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {/* Color Palette */}
            <div className="bg-slate-50 p-6 rounded-2xl border border-slate-200">
              <h4 className="font-bold text-slate-900 text-sm mb-4 flex items-center gap-2">
                <Palette className="w-4 h-4 text-pink-600" />
                Color Palette & Tokens
              </h4>
              <div className="grid grid-cols-2 gap-3">
                {Object.entries(spec.designSystem.colors || {}).map(([name, hex]) => (
                  <div key={name} className="bg-white p-3 rounded-xl border border-slate-200 flex items-center gap-3">
                    <div
                      className="w-8 h-8 rounded-lg shadow-sm border border-slate-200 shrink-0"
                      style={{ backgroundColor: hex }}
                    />
                    <div>
                      <span className="text-xs font-bold text-slate-900 capitalize block">{name}</span>
                      <span className="text-[10px] font-mono text-slate-500 uppercase">{hex}</span>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Typography & Principles */}
            <div className="bg-slate-50 p-6 rounded-2xl border border-slate-200 space-y-4">
              <div>
                <h4 className="font-bold text-slate-900 text-sm mb-2 flex items-center gap-2">
                  <Type className="w-4 h-4 text-indigo-600" />
                  Typography & Direction
                </h4>
                <p className="text-xs text-slate-600 mb-3">
                  Direction: <span className="font-semibold text-slate-800">{spec.designSystem.styleDirection}</span>
                </p>
                <div className="grid grid-cols-2 gap-2 text-xs">
                  <div className="bg-white p-2.5 rounded-lg border border-slate-200">
                    <span className="text-slate-400 block text-[10px]">Heading Font</span>
                    <span className="font-bold text-slate-800">{spec.designSystem.typography?.headingFont || 'Inter'}</span>
                  </div>
                  <div className="bg-white p-2.5 rounded-lg border border-slate-200">
                    <span className="text-slate-400 block text-[10px]">Body Font</span>
                    <span className="font-bold text-slate-800">{spec.designSystem.typography?.bodyFont || 'Inter'}</span>
                  </div>
                </div>
              </div>

              <div>
                <span className="text-xs font-bold text-slate-900 block mb-2">Component Principles:</span>
                <ul className="space-y-1 text-xs text-slate-600">
                  {spec.designSystem.componentPrinciples?.map((p, i) => (
                    <li key={i} className="flex items-center gap-1.5">
                      <span className="w-1.5 h-1.5 rounded-full bg-indigo-500" />
                      <span>{p}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};
